# Generated by Django 4.0.3 on 2022-10-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.BigIntegerField(null=True),
        ),
    ]
