# Generated by Django 4.0.3 on 2022-10-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.BigIntegerField(default=0),
        ),
    ]
